spring:
  application:
    name: enterprise-file-manager
  
  profiles:
    active: docker
  
  datasource:
    url: jdbc:mysql://filemanager-mysql:3306/enterprise_file_manager?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: filemanager
    password: filemanager_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false
      
  redis:
    host: filemanager-redis
    port: 6379
    password: 
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 3000

server:
  port: 8080
  servlet:
    context-path: /api

# JWT配置
jwt:
  secret: enterpriseFileManagerSecretKey2024
  expiration: 86400000  # 24小时

# 文件存储配置
file:
  storage:
    default-path: /cunchu
    chunk-size: 10485760  # 10MB
    max-file-size: 1073741824  # 1GB
    temp-dir: ./temp
    allowed-types: >
      image/jpeg,image/png,image/gif,image/webp,
      application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,
      application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,
      application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation,
      text/plain,application/zip,application/x-rar-compressed,application/x-7z-compressed,
      video/mp4,video/avi,video/mov,video/x-msvideo,
      audio/mpeg,audio/wav,audio/mp3

# 日志配置
logging:
  level:
    com.filemanager: DEBUG
    org.springframework.security: DEBUG
  file:
    name: ./logs/file-manager.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

# 管理员配置
admin:
  default-username: admin
  default-password: admin123
  default-email: admin@example.com

# 系统配置
system:
  default-user-quota: 1073741824  # 1GB
  max-file-size: 1073741824  # 1GB
  enable-registration: true
  enable-email-verification: false

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always