spring:
  config:
    activate:
      on-profile: docker
  
  datasource:
    url: jdbc:mysql://localhost:3306/enterprise_file_manager?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true&enabledTLSProtocols=TLSv1.2,TLSv1.3
    username: filemanager
    password: filemanager_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  redis:
    host: localhost
    port: 6379
    password: redispassword
    database: 0
  
  # 兼容性配置
  storage:
    path: /app/storage
  
  logging:
    level:
      com.filemanager: INFO
      org.springframework.security: INFO
    file:
      name: /app/logs/file-manager.log

# 文件存储配置
file:
  storage:
    path: /app/storage
    default-path: /app/storage
  
server:
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

# JWT配置
jwt:
  secret: mySecretKey12345678901234567890123456789012345678901234567890
  expiration: 86400000  # 24小时